#!/usr/bin/env python3
"""Translate all guide/ Chinese markdown files to English in en/guide/"""
import os
import re
import shutil

# Comprehensive Chinese to English translation dictionary
TRANSLATIONS = {
    # Navigation / frontmatter
    "首页": "Home",
    "使用指南": "User Guide",
    "快速开始": "Quick Start",
    "接口示例": "API Examples",
    "应用配置": "App Configuration",
    "代码配置": "Code Configuration",
    "社区交流": "Community",
    "商店": "Shop",
    "密钥获取": "Get API Key",
    "令牌获取": "Get Token",
    "目录索引": "Table of Contents",
    "上一页": "Previous",
    "下一页": "Next",
    "返回": "Back",

    # quickstart.md
    "快速获取密钥指南": "Quick API Key Guide",
    "一键获取您的 API 密钥，立即开始使用": "Get your API key in one click and start using it right away",
    "新手推荐，快速上手注册和配置流程": "Recommended for beginners, quick registration and setup process",
    "查看指南 →": "View Guide →",
    "官网地址": "Official Website",
    "主站": "Main Site",
    "备用": "Backup",
    "接口地址": "API Endpoints",
    "主站 API 接口": "Main API Endpoint",
    "备用 API 接口": "Backup API Endpoint",
    "推荐": "Recommended",
    "领取额度": "Claim Credits",
    "新人礼包": "Welcome Bonus",
    "注册领取免费额度": "Register to claim free credits",
    "福利共享": "Referral Rewards",
    "邀请好友双方获额度": "Invite friends, both get credits",
    "快速进入": "Quick Access",
    "积分兑换": "Credit Exchange",
    "兑换和管理积分": "Exchange and manage credits",
    "令牌管理": "Token Management",
    "创建和管理 API 令牌": "Create and manage API tokens",
    "个人中心": "Account Center",
    "查看账户信息": "View account information",
    "模型价格": "Model Pricing",
    "查看模型定价详情": "View model pricing details",
    "账号注册": "Account Registration",
    "注册您的账号": "Register Your Account",
    "只需简单几步，即可完成注册并开始使用枫叶AI的所有服务。注册完成后，您将获得免费的体验额度。": "Just a few simple steps to complete registration and start using all MapleAI services. After registration, you will receive free trial credits.",
    "注意填写QQ邮箱，并在邮箱内收取验证码，收件箱找不到，就到垃圾邮件箱查看": "Note: Use your QQ email and check for the verification code in your inbox. If not found, check the spam folder.",
    "点击注册": "Register Now",
    "注册流程示意图": "Registration process illustration",

    # index.md (guide)
    "上一页：首页": "Previous: Home",
    "下一页：快速开始 →": "Next: Quick Start →",

    # api-examples.md
    "接口调用示例": "API Call Examples",
    "本页面展示了如何通过不同方式调用 API 接口": "This page demonstrates how to call the API in different ways",
    "包括 cURL、Python 和其他语言/工具的使用方法": "Including usage with cURL, Python, and other languages/tools",
    "选择你熟悉的方式，快速开始接入": "Choose the method you are familiar with to get started quickly",
    "调用示例": "Call Example",
    "查看详细注释": "View Detailed Notes",
    "点击下方按钮查看该示例的逐行注释说明：": "Click the button below to view line-by-line annotation for this example:",
    "查看 cURL 注释 →": "View cURL Notes →",
    "查看 Python 注释 →": "View Python Notes →",
    "查看更多服务商配置 →": "View More Provider Configurations →",
    "常用参数说明": "Common Parameter Description",
    "参数": "Parameter",
    "类型": "Type",
    "必填": "Required",
    "说明": "Description",
    "使用的模型名称": "Model name to use",
    "对话消息列表": "List of conversation messages",
    "是否启用流式输出": "Whether to enable streaming output",
    "温度参数，控制随机性": "Temperature parameter, controls randomness",
    "更多参数请参考 API 文档。": "For more parameters, refer to the API documentation.",
    "← 快速开始": "← Quick Start",
    "应用配置 →": "App Configuration →",
    "上一页：快速开始": "Previous: Quick Start",
    "下一页：应用配置 →": "Next: App Configuration →",

    # app-config.md
    "应用配置指南": "App Configuration Guide",
    "选择你的应用，查看详细的接入配置教程。": "Choose your application to view detailed configuration tutorials.",
    "聊天应用": "Chat Applications",
    "查看教程": "View Tutorial",
    "上一页：接口示例": "Previous: API Examples",
    "下一页：代码配置 →": "Next: Code Configuration →",
    "代码配置 →": "Code Configuration →",
    "← 接口示例": "← API Examples",

    # code-config.md
    "代码配置指南": "Code Configuration Guide",
    "选择你的开发工具，查看详细的接入配置教程。": "Choose your development tool to view detailed configuration tutorials.",
    "开发工具": "Development Tools",
    "上一页：应用配置": "Previous: App Configuration",
    "下一页：社区交流 →": "Next: Community →",
    "社区交流 →": "Community →",
    "← 应用配置": "← App Configuration",

    # community.md
    "加入我们的社区，获取最新动态和技术支持。": "Join our community for the latest updates and technical support.",
    "加入社区": "Join Community",
    "加入我们": "Join Us",
    "扫码加入": "Scan to Join",
    "官方群": "Official Group",
    "交流群": "Discussion Group",
    "频道": "Channel",
    "QQ群": "QQ Group",
    "QQ频道": "QQ Channel",
    "Telegram": "Telegram",
    "点击加入": "Click to Join",
    "复制群号": "Copy Group Number",
    "上一页：代码配置": "Previous: Code Configuration",
    "下一页：商店 →": "Next: Shop →",
    "商店 →": "Shop →",
    "← 代码配置": "← Code Configuration",

    # shop.md
    "积分商店": "Credit Shop",
    "在这里购买和兑换积分": "Purchase and exchange credits here",
    "套餐选择": "Plan Selection",
    "基础套餐": "Basic Plan",
    "标准套餐": "Standard Plan",
    "高级套餐": "Premium Plan",
    "专业套餐": "Professional Plan",
    "购买": "Purchase",
    "元": "CNY",
    "积分": "Credits",
    "上一页：社区交流": "Previous: Community",
    "下一页：密钥获取 →": "Next: Get API Key →",
    "密钥获取 →": "Get API Key →",
    "← 社区交流": "← Community",

    # token.md
    "密钥获取指南": "API Key Guide",
    "令牌获取指南": "Token Guide",
    "以下是获取API密钥的详细步骤": "Here are the detailed steps to get your API key",
    "步骤": "Step",
    "登录账户": "Log in to your account",
    "进入控制台": "Enter the console",
    "创建令牌": "Create a token",
    "复制密钥": "Copy the key",
    "注意事项": "Notes",
    "请妥善保管您的密钥": "Please keep your key safe",
    "不要将密钥分享给他人": "Do not share your key with others",
    "如果密钥泄露，请立即重新生成": "If your key is leaked, regenerate it immediately",
    "上一页：商店": "Previous: Shop",

    # api-notes/provider.md
    "服务商配置": "Provider Configuration",
    "更多服务商": "More Providers",
    "本页展示了更多服务商的配置方式": "This page shows configuration methods for more providers",
    "配置说明": "Configuration Notes",
    "填入你的 API Key": "Enter your API Key",
    "选择模型": "Select Model",

    # api-notes/python.md
    "Python 调用注释": "Python Call Notes",
    "本页为「Python 调用示例」的详细注释说明": "This page provides detailed annotations for the Python call example",
    "帮助你深入理解每个请求参数的含义与用法": "helping you deeply understand the meaning and usage of each request parameter",
    "基础调用示例": "Basic Call Example",
    "请求说明": "Request Details",
    "请求头": "Headers",
    "请求体参数": "Body Parameters",
    "字段": "Field",
    "值": "Value",
    "描述": "Description",
    "请求体格式": "Request body format",
    "认证令牌": "Auth token",
    "替换为你的真实 API Key": "Replace with your real API Key",
    "调用的模型名称": "Name of the model to call",
    "对话消息列表": "List of conversation messages",
    "消息角色": "Message role",
    "可选": "Options",
    "消息内容": "Message content",
    "多轮对话示例": "Multi-turn Conversation Example",
    "通过在": "By adding multiple messages to",
    "中添加多条消息，可以实现": "you can achieve",
    "多轮对话": "multi-turn conversation",
    "角色说明": "Role Description",
    "角色": "Role",
    "用途": "Purpose",
    "设置 AI 的行为和角色": "Sets the AI's behavior and role",
    "用户发送的消息": "Messages sent by the user",
    "AI 的回复（用于上下文传递）": "AI's replies (used for context passing)",
    "安全提醒": "Security Warning",
    "替换为你的": "Replace with your",
    "真实 API Key": "real API Key",
    "不要将 API Key 提交到 GitHub 等公开仓库": "Never commit API Keys to public repositories like GitHub",
    "建议使用环境变量管理密钥": "Use environment variables to manage keys",
    "其他提示": "Other Tips",
    "不同模型的参数和返回格式可能不同，请参考实际 API 文档": "Parameters and response formats may vary between models; refer to the actual API documentation",
    "如遇到超时问题，可尝试增加": "If you encounter timeout issues, try adding",
    "参数": "parameter",
    "返回结果默认为 JSON 格式": "Responses are in JSON format by default",

    # Common app/code tutorial terms
    "配置教程": "Configuration Tutorial",
    "使用教程": "Usage Tutorial",
    "下载安装": "Download & Install",
    "下载地址": "Download Link",
    "官方网站": "Official Website",
    "配置步骤": "Configuration Steps",
    "第一步": "Step 1",
    "第二步": "Step 2",
    "第三步": "Step 3",
    "第四步": "Step 4",
    "第五步": "Step 5",
    "打开设置": "Open Settings",
    "进入设置页面": "Go to Settings page",
    "填写配置": "Fill in Configuration",
    "填写以下信息": "Fill in the following information",
    "保存配置": "Save Configuration",
    "开始使用": "Start Using",
    "测试连接": "Test Connection",
    "接口地址": "API Endpoint",
    "模型选择": "Model Selection",
    "自定义模型": "Custom Model",
    "添加模型": "Add Model",
    "选择模型": "Select Model",
    "模型列表": "Model List",
    "设置完成": "Setup Complete",
    "配置完成": "Configuration Complete",
    "点击保存": "Click Save",
    "验证配置": "Verify Configuration",
    "返回应用配置": "Back to App Configuration",
    "返回代码配置": "Back to Code Configuration",
    "返回接口示例": "Back to API Examples",
    "图片说明": "Image description",
    "截图": "Screenshot",
    "示例": "Example",
    "以下是详细的配置步骤": "Here are the detailed configuration steps",
    "按照以下步骤进行配置": "Follow the steps below to configure",
    "请确保你已经获取了 API Key": "Make sure you have obtained your API Key",
    "如果还没有，请先": "If not, please first",
    "获取 API Key": "Get API Key",
    "在左侧菜单中找到": "Find in the left menu",
    "点击添加": "Click Add",
    "输入以下信息": "Enter the following information",
    "完成配置后": "After configuration",
    "即可开始使用": "you can start using it",
    "注意": "Note",
    "提示": "Tip",
    "警告": "Warning",
    "重要": "Important",
    "相关链接": "Related Links",
    "常见问题": "FAQ",
    "解决方案": "Solution",
    "问题": "Question",
    "回答": "Answer",
    "如果遇到问题": "If you encounter issues",
    "请检查": "Please check",
    "确保": "Make sure",
    "正确填写": "Fill in correctly",
    "是否正确": "is correct",
    "是否": "whether",
    "已经": "already",
    "以上": "above",
    "以下": "below",
    "其他": "Other",
    "更多": "More",
    "详细": "Detailed",
    "简介": "Introduction",
    "特点": "Features",
    "功能": "Function",
    "支持": "Support",
    "不支持": "Not Supported",
    "免费": "Free",
    "付费": "Paid",
    "开源": "Open Source",
    "平台": "Platform",
    "版本": "Version",
    "最新版本": "Latest Version",
    "下载": "Download",
    "安装": "Install",
    "更新": "Update",
    "设置": "Settings",
    "配置": "Configuration",
    "管理": "Manage",
    "创建": "Create",
    "删除": "Delete",
    "编辑": "Edit",
    "保存": "Save",
    "取消": "Cancel",
    "确认": "Confirm",
    "完成": "Complete",
    "开始": "Start",
    "结束": "End",
    "启用": "Enable",
    "禁用": "Disable",
    "打开": "Open",
    "关闭": "Close",
    "添加": "Add",
    "移除": "Remove",
    "选择": "Select",
    "输入": "Enter",
    "复制": "Copy",
    "粘贴": "Paste",
    "搜索": "Search",
    "查看": "View",
    "刷新": "Refresh",
    "重试": "Retry",
    "成功": "Success",
    "失败": "Failed",
    "错误": "Error",
    "正确": "Correct",
    "必填": "Required",
    "可选": "Optional",
    "默认": "Default",
    "自定义": "Custom",
    "高级": "Advanced",
    "基础": "Basic",
    "标准": "Standard",
    "专业": "Professional",

    # app-specific
    "智能对话应用": "Smart Chat Application",
    "跨平台": "Cross-platform",
    "全平台": "All Platforms",
    "桌面端": "Desktop",
    "移动端": "Mobile",
    "网页版": "Web Version",
    "客户端": "Client",
    "浏览器": "Browser",
    "扩展": "Extension",
    "插件": "Plugin",
    "主题": "Theme",
    "语言": "Language",
    "中文": "Chinese",
    "英文": "English",
    "翻译": "Translation",
    "词典": "Dictionary",
    "查词": "Look Up",

    # Additional common terms found in files
    "图文教程": "Illustrated Tutorial",
    "视频教程": "Video Tutorial",
    "视频播放": "Video Player",
    "地址填写": "Fill in the address",
    "密钥": "API key",
    "模型": "model",
    "不要遗漏模型的前后缀": "Do not omit the model prefix/suffix",
    "应用": "application",
    "信息": "information",
    "包含": "include",
    "并": " and ",
    "点击跳转": "Click to go",
    "填入您的令牌": "Enter your token",
    "获取": "obtain",
    "手动": "manually",
    "供应商": "provider",
    "主机": "Host",
    "路径": "Path",
    "自己": "your own",
    "链接": "link",
    "进入": "go to",
    "地址": "address",
    "软件信息": "Software Info",
    "要素": "elements",
    "模式": "mode",
    "点获取拉取模型": "click to fetch models",
    "兼容模式": "compatibility mode",
    "原生": "native",
    "代码": "code",
    "不包含": "not include",
    "格式": "format",
    "主模型": "main model",
    "填入": "fill in",
    "商": "provider",
    "地址填写完整": "fill in the complete address",
    "环境": "environment",
    "访问": "visit",
    "页面会自动识别你的操作系统": "The page will automatically detect your operating system",
    "无需单独": "no need to separately",
    "用户建议": "user suggestions",
    "号即": " number is ",
    "包已自带": "package already includes",
    "本地": "local",
    "持续迭代": "continuous iteration",
    "后缀": "suffix",
    "前缀": "prefix",
    "你的用户名": "your username",
    "定位": "locate",
    "用户": "user",
    "可": "can",
    "为目标模型名称即可": "as the target model name",
    "聊天补全": "chat completion",
    "端点": "endpoint",
    "按": "follow",
    "自": "self",
    "小懿": "Xiaoyi",
    "小手机": "Xiaoshouji",
    "词优化器": "Prompt Optimizer",
    "勾选所有模型能力": "check all model capabilities",
    "非必要不要勾选": "do not check unless necessary",
    "控制台": "console",
    "妥善": "properly",
    "页面": "page",
    "新密钥": "new key",
    "注释": "annotation",
    "鉴权令牌": "authentication token",
    "本页为": "This page is",
    "展示了如何通过": "shows how to use",
    "发送一条用户消息": "send a user message",
    "下面的": "the following",
    "请解释一下什么是": "please explain what is",
    "请将": "please replace",
    "调用枫叶": "call MapleAI",
    "枫叶": "MapleAI",
    "数量": "quantity",
    "请替换为真实": "please replace with real",
    "发起聊天补全请求": "make a chat completion request",
    "小贴士": "Tips",
    "使用": "use",
    "指定模型": "specify model",
    "在": "in",
    "前往商城": "Go to Shop",
    "快速获取密钥": "Quick Get Key",
    "渠道": "channel",
    "通知群": "notification group",
    "用户经验交流": "user experience exchange",
    "行业资源共享": "industry resource sharing",
    "实时在线答疑": "real-time online Q&A",
    "最新": "latest",
    "微信": "WeChat",
    "讨论": "discussion",
    "加入群聊": "join group chat",
    "资源分享": "resource sharing",
    "即时通讯": "instant messaging",
    "获取并": "obtain and",
    "填写": "fill in",
    "模型与": "model and",
    "场景": "scenario",
    "直接复用现有代码": "directly reuse existing code",
    "需要": "need",
    "用于身份认证": "used for authentication",
    "快速验证": "quick verification",
    "最小可": "minimum",
    "响应处理": "response handling",
    "的方式接入兼容": "to integrate with compatible",
    "匹配": "match",
    "文件不能写注释": "files cannot contain comments",
    "输出": "output",
    "有效": "valid",
    "或本地私有": "or local private",
    "提交到公开仓库": "commit to public repositories",
    "数组中追加": "append to the array",
    "声明": "declaration",
    "利用视觉大模型分析视频内容": "Use vision models to analyze video content",
    "请先准备一个视频文件": "Please prepare a video file first",
    "找到": "find",
    "请求异常": "request exception",
    "未知": "unknown",
    "分析图片": "analyze image",
    "生成图片": "generate image",
    "最简单的调用方式": "the simplest way to call",
    "自动提取": "auto extract",
    "这张图片的内容": "the content of this image",
    "勾选": "check",
    "您": "your",
    "提供": "provided by",
    "与": "with",
    "对话": "conversation",
    "互动": "interact",
    "我": "I",
    "拉取": "pull",
    "外部": "external",
    "鸿蒙版": "HarmonyOS version",
    "兼容": "compatible",
    "酒馆": "Tavern",
    "连接": "connect",
    "来源": "source",
    "行": "line",
    "动": "dynamic",
    "提供方": "provider",
    "名称": "name",
    "改善网络兼容性": "improve network compatibility",
    "长期": "long-term",
    "工具": "tool",
    "执行": "execute",
    "能正常显示": "can display normally",
    "通过": "through",
    "启动": "launch",
    "选项即": "option to",
    "验证": "verify",
    "版": "version",
    "或者": "or",
    "以": "with",
    "模块": "module",
    "请": "please",
    "调用": "call",
    "所有": "all",
    "建议通过后端代理转发请求": "It is recommended to forward requests through a backend proxy",
    "兑换额度": "redeem credits",
    "请勿": "do not",
    "点击": "click",
    "令牌": "token",
    "前端": "frontend",
    "上下文窗口大小": "context window size",
    "帮助你快速上手接入": "help you get started quickly",
    "本页展示": "This page shows",
    "替换为": "replace with",
    "了": "",
    "直接调用": "directly call",
    "即": "i.e.",
    "常用": "commonly used",
    "线下活动组织": "offline event organization",
    "加入": "join",
    "隐私安全": "privacy security",
    "优惠活动提醒": "promotion reminders",
    "国际": "international",
    "深度交流": "in-depth exchange",
    "订阅通知": "subscribe to notifications",
    "合作对接": "business cooperation",
    "客服": "customer service",
    "化": "-ize",
    "提交到": "submit to",
    "生成回复": "generate reply",
    "能略有差异": "may vary slightly",
    "工具进行": "tools to perform",
    "不同": "different",
    "该请求会向聊天": "this request will send to chat",
    "和响应": "and response",
    "尝试": "try",
    "切勿": "never",
    "多个": "multiple",
    "缓存读取成本": "cache read cost",
    "为推理": "for inference",
    "存": "store",
    "用法": "usage",
    "请依次检查": "please check one by one",
    "文件": "file",
    "位置": "location",
    "不要把": "do not put",
    "处理和": "process and",
    "放进一个小项目中": "put into a small project",
    "目录结构": "directory structure",
    "以参考": "for reference",
    "实际": "actual",
    "读取": "read",
    "公开仓库中提交": "commit in public repository",
    "内容": "content",
    "等": "etc.",
    "建": "build",
    "编程智能体": "programming agent",
    "社区驱动": "community-driven",
    "为目标": "as target",
    "机制": "mechanism",
    "和多种云端": "and multiple cloud",
    "帧关键画面": "key frames",
    "抽取关键帧": "extract key frames",
    "是文本": "is text",
    "这个视频里发生了什么": "what happened in this video",
    "图片": "image",
    "正": "is",
    "视频生成": "video generation",
    "的": "'s",

    # code-specific
    "代码编辑器": "Code Editor",
    "开发环境": "Development Environment",
    "集成开发": "Integrated Development",
    "命令行": "Command Line",
    "终端": "Terminal",
    "工作流": "Workflow",
    "自动化": "Automation",
    "部署": "Deploy",
    "构建": "Build",
    "运行": "Run",
    "调试": "Debug",
    "测试": "Test",
    "文档": "Documentation",
    "接口": "API",
    "服务": "Service",
    "服务器": "Server",
    "数据库": "Database",
    "环境变量": "Environment Variable",
    "依赖": "Dependency",
    "包管理": "Package Management",
}

def translate_text(text):
    """Translate Chinese text to English using dictionary lookup, longest match first."""
    # Sort by length descending so longer phrases match first
    sorted_items = sorted(TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True)
    for cn, en in sorted_items:
        text = text.replace(cn, en)
    return text

def fix_links(text):
    """Convert /guide/ links to /en/guide/ links."""
    # Fix markdown links
    text = re.sub(r"\((/guide/)", r"(/en/guide/", text)
    # Fix href links
    text = re.sub(r'href="(/guide/)', r'href="/en/guide/', text)
    # Fix frontmatter links
    text = re.sub(r"link: '(/guide/)", r"link: '/en/guide/", text)
    text = re.sub(r"link: '/'\s*$", "link: '/en/'", text)
    # Fix link to home
    text = re.sub(r'href="/"\s', r'href="/en/" ', text)
    return text

def process_file(src_path, dst_path):
    """Read source Chinese file, translate, and write to destination."""
    with open(src_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Translate the text
    translated = translate_text(content)
    
    # Fix internal links
    translated = fix_links(translated)
    
    # Ensure destination directory exists
    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    
    with open(dst_path, 'w', encoding='utf-8') as f:
        f.write(translated)
    
    # Check remaining Chinese characters
    cn_chars = re.findall(r'[\u4e00-\u9fff]+', translated)
    # Filter out Chinese in code blocks
    return cn_chars

def main():
    import sys
    sys.stdout.reconfigure(encoding='utf-8')
    
    src_dir = 'guide'
    dst_dir = os.path.join('en', 'guide')
    
    total_files = 0
    files_with_remaining_cn = 0
    
    for dirpath, dirnames, filenames in os.walk(src_dir):
        for filename in sorted(filenames):
            if not filename.endswith('.md'):
                continue
            
            src_path = os.path.join(dirpath, filename)
            rel_path = os.path.relpath(src_path, src_dir)
            dst_path = os.path.join(dst_dir, rel_path)
            
            remaining = process_file(src_path, dst_path)
            total_files += 1
            
            if remaining:
                files_with_remaining_cn += 1
                unique = list(set(remaining))[:10]
                print(f"  {rel_path}: {len(remaining)} Chinese segments remaining, samples: {unique}")
            else:
                print(f"  {rel_path}: OK Fully translated")
    
    print(f"\nTotal: {total_files} files processed, {files_with_remaining_cn} with remaining Chinese text")

if __name__ == '__main__':
    main()
